### ISSUE TITLE
Load the whole Product updates page by clicking the "Show more" button

### ISSUE THREAD

**Issue by davidk2-kentico** [edison23/njord#12]
Try to implement clicking the load `Show more` button (`<button class="button_button__u6okP">Show more</button>`) and only once it's not available anymore, consider the page loaded and save its src code.
The class is only once in the page so it should be fine. Add a delay of 3 seconds after the click because the app is slow to load new content.
This is a bug because it causes false positives.

**Comment by edison23** [comment]
This has been implemented in one of the past commits.
